apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-k8s-app-demo
  annotations:
    nginx.org/server-snippets: |
      location /tree {
          return 302 /tree;
      }
    nginx.org/client-max-body-size: "4m"
spec:
  rules:
    - host: local.ecosia.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-k8s-app-demo
                port:
                  number: 8888
